script: ./gradlew -s -PbuildInfo.build.number=$TRAVIS_BUILD_NUMBER -PbuildInfo.buildUrl=https://travis-ci.org/${TRAVIS_REPO_SLUG}/builds/${TRAVIS_JOB_ID}
  -PbuildInfo.buildAgent.name=$USER -PbuildInfo.principal=$USER clean build artifactoryPublish
jdk:
- openjdk7
env:
  global:
  - secure: CwkQDwxTSEYSRoWP5MLHRnjskHdI5oZKMaYYZeQ83wNnAjUd5JpNErnOH7H7keyxWwUqzX2ywfSpQAUs3b0zpPxUVKFxqgSD6og/e9QZ2uI+9qkxRG6ntNZ56WFxNu6s4F3c3wMy3AC6/6El2ebgg58QuS4wGCfU8EXvxV/LUb8=
  - secure: L/IblBzEflVqLbWlaCBFU0Z+SXbZ46oUppVCq5eE9WhbbrPmW3/djvz9Ng+YH/kdHLVjkX2Z4Ud6wjUwBohPO/7E3clDmptkqndjdgxdZLt2uBqgVaEvaY+aquy1zJ1Oi5b1DCaNMOqwFyNom4ARZ5wqsdiYyGUhR/fobp/7k7E=
